# Generated by Django 3.2.12 on 2024-06-02 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Health_Metrics', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HealthMetric',
            new_name='Health_Metrics',
        ),
    ]
